### ISSUE TITLE
Security Issue

### ISSUE THREAD

**Issue by ousamabenyounes** [Adam182Green/slamcovoiturage#38]
Your parameters.yml file has been compromised and your login/pwd are now visible on this link:
this project
to remove it from your history:
https://help.github.com/articles/removing-sensitive-data-from-a-repository/

Change your login/pwd on all your projects...

I recommand you also to use a gitignore file on the root of your Symfony project:
https://github.com/github/gitignore/blob/master/Symfony.gitignore
This will automatically ignore your parameters.yml file, your vendors ...

Hope this will help you :)

**Comment by ThibaultPoujat** [comment]
Hello ousamabenyounes,

Thank you for your help, and for warning us, we really didn't think that one through ! We won't be making that mistake again. We're a group of IT students working on this project together, and are quite new to Symfony and GitHub.

This will indeed help us, and we thank you once again.

**Comment by ousamabenyounes** [comment]
Hello ThibaultPoujat,

Happy to see that this message will help you :).
I can give two nice recommandations for the quality of you Symfony Project.

Plug your open source project to sensioinsight...It's free and help you have the best source code for free.
https://insight.sensiolabs.com/

It's easy to use and give you insight on your security issues, quality, performance and many other metrics for free!...

I also recommand you to use yellowlab.tools to analyze your front quality ...It's an open source project, so if you don't have public url, you'll be able to use it locally (a docker image is available)
github.com/gmetais/YellowLabTools

And do not hesitate to contact me if you have any issue using this nice projects

Have a nice day!

Ousama.
